### ISSUE TITLE
TypeError: Cannot read property 'count' of null

### ISSUE THREAD

**Issue by Nachtschatten** [PrismarineJS/prismarine-windows#28]
Happens with version 2.1.0, via mineflayer version 3.2.0

Greetings. I'm learning mineflayer. So I'm trying to have my bot empty its inventory by tossing items one by one. I throw a stack of any block at its feet, the bot picks it up and starts tossing things. This works _most of the time_, but rarely the mentioned TypeError occurs.

I instantiate my bot like this:
```
const bot = mineflayer.createBot({
    host: process.argv[2],
    port: process.argv[3],
    username: process.argv[4],
    password: process.argv[5],
    auth: 'microsoft'
})
```

This is what my bot does on 'physicTick':
```
        if (bot.inventory.items().length > 0) {
            const item = bot.inventory.items()[0];
            bot.toss(item.type, null, 1, () => {});
        }
```
Full trace of the TypeError:
```
        this.selectedItem.count -= 1
             ^
TypeError: Cannot read property 'count' of null
    at Window.acceptOutsideWindowClick (C:\Users\Nachtschatten\Documents\Projects\Minecraft-Bot\node_modules\prismarine-windows\lib\Window.js:43:14)
    at Window.acceptClick (C:\Users\Nachtschatten\Documents\Projects\Minecraft-Bot\node_modules\prismarine-windows\lib\Window.js:28:14)
    at onAccepted (C:\Users\Nachtschatten\Documents\Projects\Minecraft-Bot\node_modules\mineflayer\lib\plugins\inventory.js:356:14)
    at confirmTransaction (C:\Users\Nachtschatten\Documents\Projects\Minecraft-Bot\node_modules\mineflayer\lib\plugins\inventory.js:341:7)
    at Client.<anonymous> (C:\Users\Nachtschatten\Documents\Projects\Minecraft-Bot\node_modules\mineflayer\lib\plugins\inventory.js:441:5)
    at Client.emit (node:events:378:20)
    at FullPacketParser.<anonymous> (C:\Users\Nachtschatten\Documents\Projects\Minecraft-Bot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:378:20)
    at addChunk (C:\Users\Nachtschatten\Documents\Projects\Minecraft-Bot\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Nachtschatten\Documents\Projects\Minecraft-Bot\node_modules\readable-stream\lib\_stream_readable.js:280:11)
```

Am I using `bot.toss()` wrong or is this a genuine bug?

Kind regards,
Nachtschatten

**Comment by rom1504** [comment]
hi,

you need to do await toss
otherwise you're trying to toss multiple items at once

**Comment by Nachtschatten** [comment]
Thanks for the quick help! That fixes it. Sometimes it's the simple things you just overlooked.
